# AzureADLicensing PowerShell Module Build Pipeline

trigger:
- refs/tags/*

variables:
  - group: NuGetApiKey

stages:
  - stage: Build
    jobs:
      - job: Build
        pool:
          vmImage: 'windows-latest'
        steps:
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: |
              Install-Module InvokeBuild -Force
              Install-Module PowerShellGet -Force
              Install-Module ModuleBuilder -Force
              Install-Module Pester -Force

              Invoke-Build
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: 'bin'
            ArtifactName: 'AzureADLicensing-Module'
            publishLocation: 'Container'

  - stage: Deploy
    jobs:
      - deployment: 'Deploy'
        displayName: 'Publish to PSGallery and GitHub'
        pool:
          vmImage: 'windows-latest'
        environment: 'production'
        strategy:
          runOnce:
            deploy:
              steps:
              - task: ArchiveFiles@2
                inputs:
                  rootFolderOrFile: 'AzureADLicensing-Module/AzureADLicensing'
                  includeRootFolder: true
                  archiveType: 'zip'
                  archiveFile: '$(Build.ArtifactStagingDirectory)/AzureADLicensing.zip'
                  replaceExistingArchive: true
                  verbose: true
              - task: GitHubRelease@1
                displayName: 'Create GitHub release'
                inputs:
                  gitHubConnection: GitHub
                  tagPattern: 'v*.*'
                  assets: '$(Build.ArtifactStagingDirectory)/*.zip'
              - task: PowerShell@2
                displayName: 'Publish to PowerShell Gallery'
                inputs:
                  targetType: 'inline'
                  script: |
                    Install-Module Az.Accounts -Force
                    Publish-Module -Path ".\*\" -NuGetApiKey $env:NuGetApiKey
                    workingDirectory: '$(Build.ArtifactStagingDirectory)/AzureADLicensing-Module/AzureADLicensing'